# Generated by Django 3.2.4 on 2021-07-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]